[build]
  publish = "."

[build.environment]
  GOOGLE_SHEET_ID = "1s3NBMsKi9g0zLCiYBKvDcep35C7xvNMG-8R9r9crC2M"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
