name = "xemiro-briefing"
main = "briefing-cron.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 0 * * *"]

[vars]
GOOGLE_SHEET_ID = "1s3NBMsKi9g0zLCiYBKvDcep35C7xvNMG-8R9r9crC2M"
NEWSLETTER_ENABLED = "false"
NEWSLETTER_FROM = "XEMIRO Briefing <onboarding@resend.dev>"
